const axes = [
    {
        name: "axe",
        atk: 12,
        def: 6,
        weight: 40.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/axe.gif',
    },
    {
        name: "barbarian axe",
        atk: 28,
        def: 18,
        weight: 51.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/barbarian_axe.gif',
    },
    {
        name: "battle axe",
        atk: 25,
        def: 10,
        weight: 50.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/battle_axe.gif',
    },
    {
        name: "daramian waraxe",
        atk: 39,
        def: 15,
        weight: 52.5,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/daramian_waraxe.gif',
    },
    {
        name: "daramian axe",
        atk: 17,
        def: 8,
        weight: 41.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/daramian_axe.gif',
    },
    {
        name: "double axe",
        atk: 35,
        def: 12,
        weight: 70.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/double_axe.gif',
    },
    {
        name: "dragon lance",
        atk: 47,
        def: 16,
        weight: 67.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/dragon_lance.gif',
    },
    {
        name: "dwarven axe",
        atk: 31,
        def: 19,
        weight: 82.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/dwarven_axe.gif',
    },
    {
        name: "fire axe",
        atk: 38,
        def: 16,
        weight: 40.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/fire_axe.gif',
    },
    {
        name: "golden sickle",
        atk: 13,
        def: 6,
        weight: 19.5,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/golden_sickle.gif',
    },
    {
        name: "great axe",
        atk: 52,
        def: 22,
        weight: 90.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/great_axe.gif',
    },
    {
        name: "guardian halberd",
        atk: 46,
        def: 15,
        weight: 110.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/guardian_halberd.gif',
    },
    {
        name: "halberd",
        atk: 35,
        def: 14,
        weight: 90.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/halberd.gif',
    },
    {
        name: "hand axe",
        atk: 10,
        def: 5,
        weight: 18.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/hand_axe.gif',
    },
    {
        name: "hatchet",
        atk: 15,
        def: 8,
        weight: 35.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/hatchet.gif',
    },
    {
        name: "knight axe",
        atk: 33,
        def: 21,
        weight: 59.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/knight_axe.gif',
    },
    {
        name: "naginata",
        atk: 39,
        def: 25,
        weight: 78.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/naginata.gif',
    },
    {
        name: "obsidian lance",
        atk: 34,
        def: 10,
        weight: 80.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/obsidian_lance.gif',
    },
    {
        name: "orcish axe",
        atk: 23,
        def: 12,
        weight: 45.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/orcish_axe.gif',
    },
    {
        name: "ravager's axe",
        atk: 49,
        def: 14,
        weight: 52.5,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/ravagers_axe.gif',
    },
    {
        name: "sickle",
        atk: 7,
        def: 4,
        weight: 10.5,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/sickle.gif',
    },
    {
        name: "stonecutter axe",
        atk: 50,
        def: 30,
        weight: 99.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/axes/stonecutter_axe.gif',
    },
    {
        name: "twin axe",
        atk: 45,
        def: 24,
        weight: 64.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/twin_axe.gif',
    },
    {
        name: "war axe",
        atk: 48,
        def: 10,
        weight: 61.5,
        twoHanded: true,
        imageSrc: '/assets/imgs/axes/war_axe.gif',
    }
]

module.exports = axes