const beastiary = [
  {
    name: "amazon",
    article: "an",
    ref: 0,
    hp: 110,
    xp: 60,
    loot: [
      "brown bread",
      "crystal necklace",
      "dagger",
      "gold coin",
      "leather armor",
      "sabre",
      "skull",
      "small ruby",
      "studded shield",
      "torch",
    ],
    summon: 390,
    convince: 390,
    imageSrc: "/assets/imgs/beastiary/amazon.gif",
  },
  {
    name: "ancient scarab",
    article: "an",
    ref: 1,
    hp: 1000,
    xp: 720,
    loot: [
      "ancient amulet",
      "daramian waraxe",
      "gold coin",
      "magic light wand",
      "plate armor",
      "scarab amulet",
      "scarab coin",
      "small amethyst",
      "small emerald",
    ],
    imageSrc: "/assets/imgs/beastiary/ancient_scarab.gif",
  },
  {
    name: "badger",
    article: "a",
    ref: 2,
    hp: 23,
    xp: 5,
    loot: ["meat"],
    imageSrc: "/assets/imgs/beastiary/badger.gif",
  },
  {
    name: "banshee",
    article: "a",
    ref: 3,
    hp: 1000,
    xp: 900,
    loot: [
      "black pearl",
      "blue robe",
      "candlestick",
      "crystal ring",
      "dirty cape",
      "gold coin",
      "life crystal",
      "lyre",
      "mirror",
      "poison dagger",
      "red robe",
      "ring of healing",
      "silver amulet",
      "silver brooch",
      "simple dress",
      "spellbook",
      "stone skin amulet",
      "wedding ring",
      "white pearl",
    ],
    imageSrc: "/assets/imgs/beastiary/banshee.gif",
  },
  {
    name: "bear",
    article: "a",
    ref: 4,
    hp: 80,
    xp: 23,
    loot: ["meat", "ham"],
    imageSrc: "/assets/imgs/beastiary/bear.gif",
  },
  {
    name: "behemoth",
    article: "a",
    ref: 5,
    hp: 4000,
    xp: 2500,
    loot: [
      "amphora",
      "big bone",
      "crowbar",
      "crystal necklace",
      "dark armor",
      "double axe",
      "giant sword",
      "gold coin",
      "meat",
      "pick",
      "plate armor",
      "small amethyst",
      "steel boots",
      "strange symbol",
      "two handed sword",
      "green spell wand",
    ],
    imageSrc: "/assets/imgs/beastiary/behemoth.gif",
  },
  {
    name: "beholder",
    article: "a",
    ref: 6,
    hp: 170,
    xp: 260,
    loot: [
      "beholder shield",
      "gold coin",
      "longsword",
      "morning star",
      "spellbook",
      "steel shield",
      "two handed sword",
      "wooden shield",
    ],
    imageSrc: "/assets/imgs/beastiary/beholder.gif",
  },
  {
    name: "black knight",
    article: "a",
    ref: 7,
    hp: 1800,
    xp: 1600,
    loot: [
      "battle hammer",
      "boots of haste",
      "brass legs",
      "brown bread",
      "dark armor",
      "dragon lance",
      "gold coin",
      "halberd",
      "knight armor",
      "knight legs",
      "knight axe",
      "plate armor",
      "rope",
      "ruby necklace",
      "spear",
      "steel helmet",
      "two handed sword",
      "warrior helmet",
    ],
    imageSrc: "/assets/imgs/beastiary/black_knight.gif",
  },
  {
    name: "black sheep",
    article: "a",
    ref: 8,
    hp: 20,
    loot: ["meat"],
    imageSrc: "/assets/imgs/beastiary/black_sheep.gif",
  },
  {
    name: "blue djinn",
    article: "a",
    ref: 9,
    hp: 330,
    xp: 190,
    loot: [
      "blue rose",
      "book",
      "carrot",
      "gold coin",
      "mystic turban",
      "small oil lamp",
      "small sapphire",
    ],
    imageSrc: "/assets/imgs/beastiary/blue_djinn.gif",
  },
  {
    name: "bonebeast",
    article: "a",
    ref: 10,
    hp: 515,
    xp: 580,
    loot: [
      "big bone",
      "bone",
      "bone club",
      "bone shield",
      "gold coin",
      "green mushroom",
      "plate armor",
      "skull",
    ],
    imageSrc: "/assets/imgs/beastiary/bonebeast.gif",
  },
  {
    name: "bug",
    article: "a",
    ref: 11,
    hp: 29,
    xp: 18,
    loot: ["cherry", "gold coin"],
    imageSrc: "/assets/imgs/beastiary/bug.gif",
  },
  {
    name: "cave rat",
    article: "a",
    ref: 12,
    hp: 30,
    xp: 10,
    loot: ["cheese", "cookie", "gold coin"],
    imageSrc: "/assets/imgs/beastiary/cave_rat.gif",
  },
  {
    name: "cobra",
    article: "a",
    ref: 13,
    hp: 65,
    xp: 30,
    imageSrc: "/assets/imgs/beastiary/cobra.gif",
  },
  {
    name: "crypt shambler",
    article: "a",
    ref: 14,
    hp: 330,
    xp: 195,
    loot: [
      "bone",
      "bone shield",
      "bone sword",
      "gold coin",
      "iron helmet",
      "rotten meat",
      "small diamond",
      "throwing star",
      "two handed sword",
    ],
    imageSrc: "/assets/imgs/beastiary/crypt_shambler.gif",
  },
  {
    name: "cyclops",
    article: "a",
    ref: 15,
    hp: 260,
    xp: 150,
    loot: [
      "battle shield",
      "club ring",
      "dark helmet",
      "gold coin",
      "halberd",
      "ham",
      "plate shield",
      "short sword",
      "wolf tooth chain",
    ],
    imageSrc: "/assets/imgs/beastiary/cyclops.gif",
  },
  {
    name: "deer",
    article: "a",
    ref: 16,
    hp: 25,
    loot: ["meat", "ham"],
    imageSrc: "/assets/imgs/beastiary/deer.gif",
  },
  {
    name: "demon",
    article: "a",
    ref: 17,
    hp: 8200,
    xp: 6000,
    loot: [
      "demon shield",
      "devil helmet",
      "double axe",
      "fire axe",
      "fire mushroom",
      "giant sword",
      "gold coin",
      "coconut",
      "gold ring",
      "golden legs",
      "golden sickle",
      "ice rapier",
      "magic plate armor",
      "mastermind shield",
      "might ring",
      "orb",
      "platinum amulet",
      "purple tome",
      "ring of healing",
      "small emerald",
      "stealth ring",
      "talon",
    ],
    imageSrc: "/assets/imgs/beastiary/demon.gif",
  },
  {
    name: "demon skeleton",
    article: "a",
    ref: 18,
    hp: 400,
    xp: 240,
    loot: [
      "battle hammer",
      "battle shield",
      "gold coin",
      "guardian shield",
      "iron helmet",
      "mind stone",
      "mysterious fetish",
      "throwing star",
      "torch",
    ],
    imageSrc: "/assets/imgs/beastiary/demon_skeleton.gif",
  },
  {
    name: "dog",
    article: "a",
    ref: 19,
    hp: 20,
    imageSrc: "/assets/imgs/beastiary/dog.gif",
  },
  {
    name: "dragon",
    article: "a",
    ref: 20,
    hp: 1000,
    xp: 700,
    loot: [
      "broadsword",
      "burst arrow",
      "crossbow",
      "double axe",
      "dragon ham",
      "dragon hammer",
      "dragon shield",
      "gold coin",
      "life crystal",
      "longsword",
      "mace",
      "plate legs",
      "serpent sword",
      "short sword",
      "small diamond",
      "steel helmet",
      "steel shield",
    ],
    imageSrc: "/assets/imgs/beastiary/dragon.gif",
  },
  {
    name: "dragon lord",
    article: "a",
    ref: 21,
    hp: 1900,
    xp: 2100,
    loot: [
      "book",
      "dragon ham",
      "dragon scale mail",
      "energy ring",
      "fire sword",
      "gold coin",
      "golden mug",
      "green mushroom",
      "life crystal",
      "power bolt",
      "royal helmet",
      "small sapphire",
      "strange helmet",
      "tower shield",
    ],
    imageSrc: "/assets/imgs/beastiary/dragon_lord.gif",
  },
  {
    name: "dwarf",
    article: "a",
    ref: 22,
    hp: 90,
    xp: 45,
    loot: [
      "axe",
      "copper shield",
      "dwarven ring",
      "gold coin",
      "hatchet",
      "leather legs",
      "letter",
      "pick",
      "studded armor",
      "white mushroom",
    ],
    imageSrc: "/assets/imgs/beastiary/dwarf.gif",
  },
  {
    name: "dwarf geomancer",
    article: "a",
    ref: 23,
    hp: 380,
    xp: 245,
    loot: [
      "blank rune",
      "clerical mace",
      "dwarven ring",
      "gold coin",
      "leather boots",
      "magic light wand",
      "pear",
      "small sapphire",
      "soldier helmet",
      "spellbook",
      "studded legs",
      "white mushroom",
    ],
    imageSrc: "/assets/imgs/beastiary/dwarf_geomancer.gif",
  },
  {
    name: "dwarf guard",
    article: "a",
    ref: 24,
    hp: 245,
    xp: 170,
    loot: [
      "axe ring",
      "battle hammer",
      "battle shield",
      "double axe",
      "gold coin",
      "leather boots",
      "scale armor",
      "small amethyst",
      "steel helmet",
      "white mushroom",
    ],
    imageSrc: "/assets/imgs/beastiary/dwarf_guard.gif",
  },
  {
    name: "dwarf soldier",
    article: "a",
    ref: 25,
    hp: 135,
    xp: 70,
    loot: [
      "axe ring",
      "battle axe",
      "bolt",
      "chain armor",
      "crossbow",
      "dwarven shield",
      "gold coin",
      "shovel",
      "soldier helmet",
      "white mushroom",
    ],
    imageSrc: "/assets/imgs/beastiary/dwarf_soldier.gif",
  },
  {
    name: "efreet",
    article: "an",
    ref: 26,
    hp: 550,
    xp: 300,
    loot: [
      "gold coin",
      "green gem",
      "green tapestry",
      "heavy machete",
      "mystic turban",
      "pear",
      "small emerald",
      "small oil lamp",
    ],
    imageSrc: "/assets/imgs/beastiary/efreet.gif",
  },
  {
    name: "elder beholder",
    article: "an",
    ref: 27,
    hp: 500,
    xp: 280,
    loot: [
      "beholder shield",
      "gold coin",
      "longsword",
      "carlin sword",
      "spellbook",
      "steel shield",
      "two handed sword",
    ],
    imageSrc: "/assets/imgs/beastiary/elder_beholder.gif",
  },
  {
    name: "elf",
    article: "an",
    ref: 28,
    hp: 100,
    xp: 42,
    loot: [
      "arrow",
      "brass shield",
      "leather boots",
      "longsword",
      "red apple",
      "studded armor",
      "studded helmet",
    ],
    imageSrc: "/assets/imgs/beastiary/elf.gif",
  },
  {
    name: "elf arcanist",
    article: "an",
    ref: 29,
    hp: 220,
    xp: 175,
    loot: [
      "arrow",
      "blank rune",
      "bowl",
      "bread",
      "candlestick",
      "elven amulet",
      "grave flower",
      "green tunic",
      "inkwell",
      "life crystal",
      "melon",
      "sandals",
      "scroll",
      "sling herb",
      "staff",
      "yellow gem",
    ],
    imageSrc: "/assets/imgs/beastiary/elf_arcanist.gif",
  },
  {
    name: "elf scout",
    article: "an",
    ref: 30,
    hp: 160,
    xp: 75,
    loot: [
      "arrow",
      "bow",
      "gold coin",
      "grapes",
      "longsword",
      "poison arrow",
      "sandals",
      "studded armor",
      "studded helmet",
      "waterskin",
    ],
    imageSrc: "/assets/imgs/beastiary/elf_scout.gif",
  },
  {
    name: "fire devil",
    article: "a",
    ref: 31,
    hp: 200,
    xp: 110,
    loot: [
      "blank rune",
      "cleaver",
      "double axe",
      "guardian shield",
      "pitchfork",
      "scimitar",
      "small amethyst",
      "torch",
      "red spell wand",
    ],
    imageSrc: "/assets/imgs/beastiary/fire_devil.gif",
  },
  {
    name: "fire elemental",
    article: "a",
    ref: 32,
    hp: 280,
    xp: 220,
    imageSrc: "/assets/imgs/beastiary/fire_elemental.gif",
  },
  {
    name: "frost troll",
    article: "a",
    ref: 33,
    hp: 55,
    xp: 23,
    loot: [
      "club",
      "coat",
      "fish",
      "gold coin",
      "rapier",
      "spear",
      "twigs",
      "wooden shield",
    ],
    imageSrc: "/assets/imgs/beastiary/frost_troll.gif",
  },
  {
    name: "gargoyle",
    article: "a",
    ref: 34,
    hp: 250,
    xp: 150,
    loot: [
      "battle shield",
      "club ring",
      "dark armor",
      "gold coin",
      "ham",
      "meat",
      "morning star",
      "small stone",
      "steel helmet",
      "studded club",
      "wolf tooth chain",
    ],
    imageSrc: "/assets/imgs/beastiary/gargoyle.gif",
  },
  {
    name: "gazer",
    article: "a",
    ref: 35,
    hp: 120,
    xp: 90,
    loot: ["gold coin", "wooden shield"],
    imageSrc: "/assets/imgs/beastiary/gazer.gif",
  },
  {
    name: "ghost",
    article: "a",
    ref: 36,
    hp: 150,
    xp: 120,
    loot: [
      "ancient shield",
      "book",
      "cape",
      "combat knife",
      "morning star",
      "sandals",
      "shadow herb",
      "stealth ring",
      "golden wand",
    ],
    imageSrc: "/assets/imgs/beastiary/ghost.gif",
  },
  {
    name: "ghoul",
    article: "a",
    ref: 37,
    hp: 100,
    xp: 85,
    loot: [
      "brass helmet",
      "gold coin",
      "knife",
      "life ring",
      "scale armor",
      "skull",
      "torch",
      "viking helmet",
    ],
    imageSrc: "/assets/imgs/beastiary/bear.gif",
  },
  {
    name: "giant spider",
    article: "a",
    ref: 38,
    hp: 1300,
    xp: 900,
    loot: [
      "brass legs",
      "gold coin",
      "knight armor",
      "knight legs",
      "plate armor",
      "platinum amulet",
      "steel helmet",
      "time ring",
    ],
    imageSrc: "/assets/imgs/beastiary/giant_spider.gif",
  },
  {
    name: "goblin",
    article: "a",
    ref: 39,
    hp: 50,
    xp: 25,
    loot: [
      "bone",
      "bone club",
      "dagger",
      "fish",
      "gold coin",
      "leather armor",
      "leather helmet",
      "moldy cheese",
      "short sword",
      "small axe",
      "small stone",
    ],
    imageSrc: "/assets/imgs/beastiary/goblin.gif",
  },
  {
    name: "green djinn",
    article: "a",
    ref: 40,
    hp: 330,
    xp: 190,
    loot: [
      "book",
      "cheese",
      "gold coin",
      "grave flower",
      "mystic turban",
      "small emerald",
      "small oil lamp",
    ],
    imageSrc: "/assets/imgs/beastiary/green_djinn.gif",
  },
  {
    name: "hero",
    article: "a",
    ref: 41,
    hp: 1400,
    xp: 1200,
    loot: [
      "arrow",
      "bow",
      "crown armor",
      "crown helmet",
      "crown legs",
      "crown shield",
      "fire sword",
      "gold coin",
      "grapes",
      "green tunic",
      "lyre",
      "meat",
      "might ring",
      "red rose",
      "rope",
      "scarf",
      "scroll",
      "two handed sword",
      "war hammer",
      "wedding ring",
    ],
    imageSrc: "/assets/imgs/beastiary/hero.gif",
  },
  {
    name: "hunter",
    article: "a",
    ref: 42,
    hp: 150,
    xp: 150,
    loot: [
      "arrow",
      "bow",
      "brass armor",
      "brass helmet",
      "burst arrow",
      "dragon necklace",
      "leather helmet",
      "leather legs",
      "orange",
      "roll",
      "small ruby",
      "torch",
    ],
    imageSrc: "/assets/imgs/beastiary/hunter.gif",
  },
  {
    name: "hyaena",
    article: "a",
    ref: 43,
    hp: 60,
    xp: 20,
    loot: ["meat"],
    imageSrc: "/assets/imgs/beastiary/hyaena.gif",
  },
  {
    name: "larva",
    article: "a",
    ref: 44,
    hp: 70,
    xp: 44,
    loot: ["gold coin", "meat"],
    imageSrc: "/assets/imgs/beastiary/larva.gif",
  },
  {
    name: "lich",
    article: "a",
    ref: 45,
    hp: 880,
    xp: 900,
    loot: [
      "black pearl",
      "blue robe",
      "castle shield",
      "dirty cape",
      "gold coin",
      "mind stone",
      "platinum amulet",
      "ring of healing",
      "spellbook",
      "staff",
      "strange helmet",
      "white pearl",
    ],
    imageSrc: "/assets/imgs/beastiary/lich.gif",
  },
  {
    name: "lion",
    article: "a",
    ref: 46,
    hp: 80,
    xp: 30,
    loot: ["meat", "ham"],
    imageSrc: "/assets/imgs/beastiary/lion.gif",
  },
  {
    name: "marid",
    article: "a",
    ref: 47,
    hp: 550,
    xp: 300,
    loot: [
      "blue gem",
      "blue tapestry",
      "blueberry",
      "gold coin",
      "heavy machete",
      "mystic turban",
      "small oil lamp",
      "small sapphire",
      "wooden flute",
    ],
    imageSrc: "/assets/imgs/beastiary/marid.gif",
  },
  {
    name: "minotaur",
    article: "a",
    ref: 48,
    hp: 100,
    xp: 50,
    loot: [
      "axe",
      "brass helmet",
      "bronze amulet",
      "chain armor",
      "chain helmet",
      "gold coin",
      "leather legs",
      "mace",
      "meat",
      "plate shield",
      "shovel",
      "sword",
    ],
    imageSrc: "/assets/imgs/beastiary/minotaur.gif",
  },
  {
    name: "minotaur archer",
    article: "a",
    ref: 49,
    hp: 100,
    xp: 65,
    loot: [
      "bolt",
      "brass armor",
      "crossbow",
      "gold coin",
      "leather helmet",
      "leather legs",
      "meat",
      "scale armor",
      "soldier helmet",
    ],
    imageSrc: "/assets/imgs/beastiary/minotaur_archer.gif",
  },
  {
    name: "minotaur guard",
    article: "a",
    ref: 50,
    hp: 185,
    xp: 160,
    loot: [
      "battle shield",
      "brass armor",
      "chain armor",
      "chain legs",
      "double axe",
      "fishing rod",
      "gold coin",
      "hatchet",
      "leather legs",
      "meat",
    ],
    imageSrc: "/assets/imgs/beastiary/minotaur_guard.gif",
  },
  {
    name: "minotaur mage",
    article: "a",
    ref: 51,
    hp: 155,
    xp: 150,
    loot: [
      "brass armor",
      "carrot",
      "chain legs",
      "combat knife",
      "dead snake",
      "gold coin",
      "knife",
      "leather helmet",
      "leather legs",
      "torch",
    ],
    imageSrc: "/assets/imgs/beastiary/minotaur_mage.gif",
  },
  {
    name: "monk",
    article: "a",
    ref: 52,
    hp: 240,
    xp: 200,
    loot: [
      "ankh",
      "bread",
      "brown flask",
      "gold coin",
      "leather armor",
      "life crystal",
      "lamp",
      "power ring",
      "sandals",
      "scroll",
      "staff",
    ],
    imageSrc: "/assets/imgs/beastiary/monk.gif",
  },
  {
    name: "mummy",
    article: "a",
    ref: 53,
    hp: 240,
    xp: 150,
    loot: [
      "black pearl",
      "black shield",
      "crystal ring",
      "gold coin",
      "magic light wand",
      "poison dagger",
      "short sword",
      "silver amulet",
      "silver brooch",
      "strange talisman",
    ],
    imageSrc: "/assets/imgs/beastiary/mummy.gif",
  },
  {
    name: "necromancer",
    article: "a",
    ref: 54,
    hp: 580,
    xp: 580,
    loot: [
      "boots of haste",
      "clerical mace",
      "gold coin",
      "green mushroom",
      "mystic turban",
      "scale armor",
      "short sword",
      "skull staff",
      "conjurer wand",
    ],
    imageSrc: "/assets/imgs/beastiary/necromancer.gif",
  },
  {
    name: "orc",
    article: "an",
    ref: 55,
    hp: 70,
    xp: 25,
    loot: [
      "axe",
      "gold coin",
      "meat",
      "studded armor",
      "studded helmet",
      "studded shield",
    ],
    imageSrc: "/assets/imgs/beastiary/orc.gif",
  },
  {
    name: "orc berserker",
    article: "an",
    ref: 56,
    hp: 210,
    xp: 195,
    loot: [
      "battle axe",
      "chain armor",
      "chain helmet",
      "gold coin",
      "halberd",
      "ham",
      "lamp",
    ],
    imageSrc: "/assets/imgs/beastiary/orc_berserker.gif",
  },
  {
    name: "orc leader",
    article: "an",
    ref: 57,
    hp: 450,
    xp: 270,
    loot: [
      "backpack",
      "brass legs",
      "broadsword",
      "dagger",
      "fish",
      "gold coin",
      "longsword",
      "meat",
      "plate armor",
      "plate legs",
      "plate shield",
      "scimitar",
      "sword ring",
      "throwing knife",
      "warrior helmet",
    ],
    imageSrc: "/assets/imgs/beastiary/orc_leader.gif",
  },
  {
    name: "orc rider",
    article: "an",
    ref: 58,
    hp: 180,
    xp: 110,
    loot: [
      "backpack",
      "battle shield",
      "gold coin",
      "meat",
      "obsidian lance",
      "orcish axe",
      "scale armor",
      "studded helmet",
      "torch",
      "wolf tooth chain",
    ],
    imageSrc: "/assets/imgs/beastiary/orc_rider.gif",
  },
  {
    name: "orc shaman",
    article: "an",
    ref: 59,
    hp: 115,
    xp: 110,
    loot: [
      "book",
      "chain armor",
      "chain helmet",
      "corncob",
      "gold coin",
      "spear",
      "staff",
      "blue spell wand",
    ],
    imageSrc: "/assets/imgs/beastiary/orc_shaman.gif",
  },
  {
    name: "orc spearman",
    article: "an",
    ref: 60,
    hp: 105,
    xp: 38,
    loot: [
      "dirty fur",
      "gold coin",
      "machete",
      "meat",
      "spear",
      "studded helmet",
      "studded legs",
    ],
    imageSrc: "/assets/imgs/beastiary/orc_spearman.gif",
  },
  {
    name: "orc warlord",
    article: "an",
    ref: 61,
    hp: 950,
    xp: 670,
    loot: [
      "brass armor",
      "brass legs",
      "crusader helmet",
      "dark helmet",
      "dragon hammer",
      "fish",
      "gold coin",
      "meat",
      "orcish axe",
      "plate armor",
      "plate legs",
      "protection amulet",
      "scimitar",
      "stealth ring",
      "throwing star",
      "two handed sword",
    ],
    imageSrc: "/assets/imgs/beastiary/orc_warlord.gif",
  },
  {
    name: "orc warrior",
    article: "an",
    ref: 62,
    hp: 125,
    xp: 50,
    loot: [
      "bottle",
      "chain armor",
      "copper shield",
      "gold coin",
      "meat",
      "poison dagger",
      "sabre",
      "wooden shield",
    ],
    imageSrc: "/assets/imgs/beastiary/orc_warrior.gif",
  },
  {
    name: "pig",
    article: "a",
    ref: 63,
    hp: 25,
    loot: ["meat"],
    imageSrc: "/assets/imgs/beastiary/pig.gif",
  },
  {
    name: "poison spider",
    article: "a",
    ref: 64,
    hp: 26,
    xp: 22,
    loot: ["gold coin"],
    imageSrc: "/assets/imgs/beastiary/poison_spider.gif",
  },
  {
    name: "polar bear",
    article: "a",
    ref: 65,
    hp: 85,
    xp: 28,
    loot: ["meat", "ham"],
    imageSrc: "/assets/imgs/beastiary/polar_bear.gif",
  },
  {
    name: "priestess",
    article: "a",
    ref: 66,
    hp: 390,
    xp: 420,
    loot: [
      "black shield",
      "book",
      "bowl",
      "clerical mace",
      "crystal ball",
      "crystal necklace",
      "dagger",
      "goat grass",
      "powder herb",
      "red apple",
      "sling herb",
      "talon",
      "wood mushroom",
      "wooden flute",
    ],
    imageSrc: "/assets/imgs/beastiary/priestess.gif",
  },
  {
    name: "rabbit",
    article: "a",
    ref: 67,
    hp: 15,
    loot: ["carrot", "meat"],
    imageSrc: "/assets/imgs/beastiary/rabbit.gif",
  },
  {
    name: "rat",
    article: "a",
    ref: 68,
    hp: 20,
    xp: 5,
    loot: ["cheese", "gold coin"],
    imageSrc: "/assets/imgs/beastiary/rat.gif",
  },
  {
    name: "rotworm",
    article: "a",
    ref: 69,
    hp: 65,
    xp: 40,
    loot: [
      "copper shield",
      "gold coin",
      "ham",
      "katana",
      "legion helmet",
      "mace",
      "meat",
      "sword",
    ],
    imageSrc: "/assets/imgs/beastiary/rotworm.gif",
  },
  {
    name: "scarab",
    article: "a",
    ref: 70,
    hp: 320,
    xp: 120,
    loot: [
      "arrow",
      "daramian mace",
      "gold coin",
      "heavy machete",
      "meat",
      "scarab coin",
      "small amethyst",
      "small emerald",
    ],
    imageSrc: "/assets/imgs/beastiary/scarab.gif",
  },
  {
    name: "scorpion",
    article: "a",
    ref: 71,
    hp: 45,
    xp: 45,
    imageSrc: "/assets/imgs/beastiary/scorpion.gif",
  },
  {
    name: "sheep",
    article: "a",
    ref: 72,
    hp: 20,
    loot: ["meat"],
    imageSrc: "/assets/imgs/beastiary/sheep.gif",
  },
  {
    name: "skeleton",
    article: "a",
    ref: 73,
    hp: 50,
    xp: 35,
    loot: [
      "bone",
      "brass shield",
      "gold coin",
      "hatchet",
      "mace",
      "sword",
      "torch",
      "viking helmet",
    ],
    imageSrc: "/assets/imgs/beastiary/skeleton.gif",
  },
  {
    name: "skunk",
    article: "a",
    ref: 74,
    hp: 20,
    xp: 3,
    loot: ["meat"],
    imageSrc: "/assets/imgs/beastiary/skunk.gif",
  },
  {
    name: "slime",
    article: "a",
    ref: 75,
    hp: 150,
    xp: 160,
    imageSrc: "/assets/imgs/beastiary/slime.gif",
  },
  {
    name: "snake",
    article: "a",
    ref: 76,
    hp: 15,
    xp: 10,
    imageSrc: "/assets/imgs/beastiary/snake.gif",
  },
  {
    name: "stalker",
    article: "a",
    ref: 77,
    hp: 120,
    xp: 90,
    loot: [
      "backpack",
      "blank rune",
      "brass legs",
      "brass shield",
      "gold coin",
      "katana",
      "leather legs",
      "obsidian lance",
      "throwing knife",
    ],
    imageSrc: "/assets/imgs/beastiary/stalker.gif",
  },
  {
    name: "stone golem",
    article: "a",
    ref: 78,
    hp: 270,
    xp: 160,
    loot: [
      "carlin sword",
      "crystal ring",
      "gold coin",
      "power ring",
      "red gem",
      "scale armor",
      "small stone",
      "steel shield",
      "torch",
    ],
    imageSrc: "/assets/imgs/beastiary/stone_golem.gif",
  },
  {
    name: "swamp troll",
    article: "a",
    ref: 79,
    hp: 55,
    xp: 25,
    loot: [
      "dagger",
      "fish",
      "fishing rod",
      "gold coin",
      "leather boots",
      "torch",
    ],
    imageSrc: "/assets/imgs/beastiary/swamp_troll.gif",
  },
  {
    name: "troll",
    article: "a",
    ref: 80,
    hp: 50,
    xp: 20,
    loot: [
      "gold coin",
      "hand axe",
      "leather boots",
      "leather helmet",
      "meat",
      "rope",
      "silver amulet",
      "spear",
      "studded club",
      "wooden shield",
    ],
    imageSrc: "/assets/imgs/beastiary/troll.gif",
  },
  {
    name: "valkyrie",
    article: "a",
    ref: 81,
    hp: 190,
    xp: 85,
    loot: [
      "chain armor",
      "chain helmet",
      "dagger",
      "double axe",
      "gold coin",
      "meat",
      "plate armor",
      "protection amulet",
      "red apple",
      "skull",
      "small diamond",
      "spear",
    ],
    imageSrc: "/assets/imgs/beastiary/valkyrie.gif",
  },
  {
    name: "vampire",
    article: "a",
    ref: 82,
    hp: 450,
    xp: 290,
    loot: [
      "black pearl",
      "bowl",
      "bronze amulet",
      "emerald bangle",
      "gold coin",
      "grave flower",
      "ice rapier",
      "katana",
      "leather legs",
      "skull",
      "spike sword",
      "strange helmet",
      "vampire shield",
    ],
    imageSrc: "/assets/imgs/beastiary/vampire.gif",
  },
  {
    name: "war wolf",
    article: "a",
    ref: 83,
    hp: 140,
    xp: 55,
    loot: ["meat", "ham"],
    imageSrc: "/assets/imgs/beastiary/war_wolf.gif",
  },
  {
    name: "warlock",
    article: "a",
    ref: 84,
    hp: 4000,
    xp: 3200,
    loot: [
      "blue robe",
      "bread",
      "candlestick",
      "cherry",
      "crystal ring",
      "dark mushroom",
      "energy ring",
      "gold coin",
      "golden armor",
      "inkwell",
      "mind stone",
      "poison dagger",
      "red tome",
      "ring of the sky",
      "skull staff",
      "small sapphire",
      "stone skin amulet",
      "talon",
      "wand of might",
    ],
    imageSrc: "/assets/imgs/beastiary/warlock.gif",
  },
  {
    name: "wasp",
    article: "a",
    ref: 85,
    hp: 35,
    xp: 24,
    imageSrc: "/assets/imgs/beastiary/wasp.gif",
  },
  {
    name: "wild warrior",
    article: "a",
    ref: 86,
    hp: 120,
    xp: 55,
    loot: [
      "axe",
      "brass armor",
      "brass shield",
      "leather boots",
      "doll",
      "gold coin",
      "iron helmet",
      "leather legs",
      "mace",
      "meat",
      "steel shield",
      "war hammer",
    ],
    imageSrc: "/assets/imgs/beastiary/wild_warrior.gif",
  },
  {
    name: "winter wolf",
    article: "a",
    ref: 87,
    hp: 30,
    xp: 20,
    loot: ["meat"],
    imageSrc: "/assets/imgs/beastiary/winter_wolf.gif",
  },
  {
    name: "witch",
    article: "a",
    ref: 88,
    hp: 300,
    xp: 120,
    loot: [
      "broom",
      "cape",
      "cheese",
      "coat",
      "cookie",
      "garlic necklace",
      "gold coin",
      "leather boots",
      "sickle",
      "silver dagger",
      "star herb",
      "wolf tooth chain",
    ],
    imageSrc: "/assets/imgs/beastiary/witch.gif",
  },
  {
    name: "wolf",
    article: "a",
    ref: 89,
    hp: 25,
    xp: 18,
    loot: ["meat"],
    imageSrc: "/assets/imgs/beastiary/wolf.gif",
  },
  {
    name: "yeti",
    article: "a",
    ref: 90,
    hp: 950,
    xp: 460,
    loot: [
      "bunnyslippers",
      "gold coin",
      "ham",
      "meat",
      "snowball",
      "wolf tooth chain",
    ],
    imageSrc: "/assets/imgs/beastiary/yeti.gif",
  },
  {
    name: "alphadyte",
    article: "an",
    ref: 91,
    hp: 750,
    xp: 480,
    loot: [
      "big bone",
      "battle shield",
      "plate armor",
      "meat",
      "gold coin",
      "small diamond",
      "skull",
      "small rock crystal",
    ],
    imageSrc: "/assets/imgs/beastiary/alphadyte.gif",
  },
  {
    name: "desert hunter",
    article: "a",
    ref: 92,
    hp: 180,
    xp: 230,
    loot: [
      "gold coin",
      "leather helmet",
      "arrow",
      "power arrow",
      "meat",
      "burst arrow",
      "bow",
      "brass armor",
      "leather legs",
      "poison arrow",
      "foil",
    ],
    imageSrc: "/assets/imgs/beastiary/desert_hunter.gif",
  },
  {
    name: "gorlak",
    article: "a",
    ref: 93,
    hp: 80,
    xp: 40,
    loot: [
      "brown mushroom",
      "gold coin",
      "studded club",
      "small emerald",
      "fishbone",
      "worn leather boots",
      "moldy cheese",
    ],
    imageSrc: "/assets/imgs/beastiary/gorlak.gif",
  },
  {
    name: "kobold",
    article: "a",
    ref: 94,
    hp: 120,
    xp: 60,
    loot: [
      "gold coin",
      "meat",
      "spear",
      "wooden shield",
      "silver dagger",
      "studded armor",
      "small ruby",
      "small sapphire",
      "studded legs",
      "dirty fur",
    ],
    imageSrc: "/assets/imgs/beastiary/kobold.gif",
  },
  {
    name: "kobold stoneshooter",
    article: "a",
    ref: 95,
    hp: 150,
    xp: 100,
    loot: [
      "gold coin",
      "brass armor",
      "meat",
      "brass legs",
      "brass helmet",
      "rapier",
      "small stone",
      "native armor",
      "copper shield",
      "protection amulet",
      "red grapefruit",
    ],
    imageSrc: "/assets/imgs/beastiary/kobold_stoneshooter.gif",
  },
  {
    name: "magma beast",
    article: "a",
    ref: 96,
    hp: 5500,
    xp: 3300,
    loot: [
      "gold coin",
      "talon",
      "tower shield",
      "burst arrow",
      "strange helmet",
      "dark armor",
      "broadsword",
      "obsidian lance",
      "small ruby",
      "stone skin amulet",
      "might ring",
      "red gem",
      "hammer of wrath",
    ],
    imageSrc: "/assets/imgs/beastiary/magma_beast.gif",
  },
  {
    name: "obliterator",
    xp: 14900,
    article: "an",
    ref: 97,
    imageSrc: "/assets/imgs/beastiary/obliterator.gif",
  },
  {
    name: "sandlord",
    article: "a",
    ref: 98,
    hp: 4000,
    xp: 4800,
    loot: ["red robe", "bright sword", "talon", "small ruby"],
    imageSrc: "/assets/imgs/beastiary/sandlord.gif",
  },
  {
    name: "troglodyte",
    article: "a",
    ref: 99,
    hp: 220,
    xp: 380,
    loot: [
      "fish",
      "spear",
      "bone",
      "gold coin",
      "bone shield",
      "remains of a fish",
      "scale armor",
      "mace",
      "brass legs",
      "rotten meat",
    ],
    imageSrc: "/assets/imgs/beastiary/troglodyte.gif",
  },
  {
    name: "underworm",
    article: "an",
    ref: 100,
    hp: 2500,
    xp: 1700,
    loot: [
      "brass legs",
      "iron helmet",
      "gold coin",
      "meat",
      "battle hammer",
      "ham",
      "two handed sword",
      "brass armor",
      "skull",
      "skeleton",
      "big bone",
      "dark shield",
      "axe ring",
      "guardian halberd",
    ],
    imageSrc: "/assets/imgs/beastiary/underworm.gif",
  },
  {
    name: "Ferumbras",
    ref: 101,
    article: "",
    imageSrc: "/assets/imgs/beastiary/ferumbras.gif",
  },
  {
    name: "Orshabaal",
    article: "",
    ref: 102,
    hp: 22500,
    xp: 9999,
    loot: [
      "gold coin",
      "platinum coin",
      "black pearl",
      "gold ingot",
      "orb",
      "small amethyst",
      "small diamond",
      "small emerald",
      "small sapphire",
      "talon",
      "ancient amulet",
      "blue gem",
      "boots of haste",
      "crystal ball",
      "crystal necklace",
      "crystal ring",
      "demon shield",
      "devil helmet",
      "double axe",
      "dragon hammer",
      "fire axe",
      "giant sword",
      "gold ring",
      "golden legs",
      "golden mug",
      "golden sickle",
      "green gem",
      "life crystal",
      "magic light wand",
      "magic plate armor",
      "mastermind shield",
      "might ring",
      "mind stone",
      "platinum amulet",
      "protection amulet",
      "purple tome",
      "ring of healing",
      "ring of the sky",
      "silver amulet",
      "silver dagger",
      "stone skin amulet",
      "strange symbol",
      "two handed sword",
      "teddy bear",
      "thunder hammer",
    ],
    imageSrc: "/assets/imgs/beastiary/demon.gif",
  },
  {
    name: "overseer",
    article: "an",
    ref: 103,
    hp: 290,
    xp: 430,
    loot: [
      "gold coin",
      "dark armor",
      "brass legs",
      "torch",
      "ham",
      "strange helmet",
      "morning star",
    ],
    imageSrc: "/assets/imgs/beastiary/overseer.gif",
  },
  {
    name: "tar",
    article: "a",
    ref: 104,
    hp: 240,
    xp: 260,
    imageSrc: "/assets/imgs/beastiary/tar.gif",
  },
  {
    name: "spider",
    article: "a",
    ref: 105,
    hp: 20,
    xp: 12,
    loot: ["gold coin"],
    imageSrc: "/assets/imgs/beastiary/spider.gif",
  },
];

module.exports = beastiary;
