const clubs = [
    {
        name: "arcane staff",
        atk: 50,
        def: 30,
        weight: 40.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/clubs/arcane_staff.gif',
    },
    {
        name: "battle hammer",
        atk: 24,
        def: 14,
        weight: 68.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/battle_hammer.gif',
    },
    {
        name: "bone club",
        atk: 12,
        def: 8,
        weight: 39.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/bone_club.gif',
    },
    {
        name: "clerical mace",
        atk: 28,
        def: 15,
        weight: 58.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/clerical_mace.gif',
    },
    {
        name: "club",
        atk: 7,
        def: 7,
        weight: 25.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/club.gif',
    },
    {
        name: "crowbar",
        atk: 6,
        def: 6,
        weight: 21.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/crowbar.gif',
    },
    {
        name: "crystal mace",
        atk: 38,
        def: 16,
        weight: 80.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/crystal_mace.gif',
    },
    {
        name: "daramian mace",
        atk: 21,
        def: 12,
        weight: 68.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/daramian_mace.gif',
    },
    {
        name: "dragon hammer",
        atk: 32,
        def: 20,
        weight: 97.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/dragon_hammer.gif',
    },
    {
        name: "golden mace",
        atk: 0,
        def: 0,
        weight: 0.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/golden_mace.gif',
    },
    {
        name: "hammer of wrath",
        atk: 48,
        def: 12,
        weight: 70.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/clubs/hammer_of_wrath.gif',
    },
    {
        name: "heavy mace",
        atk: 49,
        def: 15,
        weight: 110.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/clubs/heavy_mace.gif',
    },
    {
        name: "iron hammer",
        atk: 18,
        def: 10,
        weight: 66.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/iron_hammer.gif',
    },
    {
        name: "mace",
        atk: 16,
        def: 11,
        weight: 38.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/mace.gif',
    },
    {
        name: "morning star",
        atk: 25,
        def: 11,
        weight: 54.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/morning_star.gif',
    },
    {
        name: "scythe",
        atk: 8,
        def: 3,
        weight: 30.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/clubs/scythe.gif',
    },
    {
        name: "silver mace",
        atk: 40,
        def: 30,
        weight: 67.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/silver_mace.gif',
    },
    {
        name: "skull staff",
        atk: 36,
        def: 12,
        weight: 17.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/skull_staff.gif',
    },
    {
        name: "studded club",
        atk: 9,
        def: 8,
        weight: 35.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/studded_club.gif',
    },
    {
        name: "thunder hammer",
        atk: 49,
        def: 35,
        weight: 125.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/thunder_hammer.gif',
    },
    {
        name: "war hammer",
        atk: 45,
        def: 10,
        weight: 85.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/clubs/war_hammer.gif',
    },
    {
        name: "staff",
        atk: 10,
        def: 25,
        weight: 38.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/clubs/staff.gif',
    },
    {
        name: "enchanted staff",
        atk: 39,
        def: 45,
        weight: 38.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/clubs/enchanted_staff.gif',
    },
    {
        name: "?",
        atk: 0,
        def: 0,
        weight: 0.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/clubs/6894.gif',
    }
]

module.exports = clubs