/* 
    GROUPS
    Support - 0
    Healing - 1
    Attack - 2
*/

const spells = [
    {
        name: "animate dead rune",
        invocation: "adana mort",
        vocations: [3, 4, 5, 6],
        group: 0,
        isRune: true,
        isPremium: true,
        mlCast: 7,
        mana: 300,
        price: 1200,
        charges: 2,
        mlUse: 4,
        imgSrc: "/assets/imgs/runes/animate_dead.gif"
    },
    {
        name: "antidote",
        invocation: "exana pox",
        vocations: [1, 2, 3, 4, 5, 6, 7, 8],
        group: 1,
        isRune: false,
        isPremium: false,
        mlCast: 2,
        mana: 30,
        price: 150
    },
    {
        name: "antidote rune",
        invocation: "adana pox",
        vocations: [5, 6],
        group: 1,
        isRune: true,
        isPremium: false,
        mlCast: 5,
        mana: 50,
        price: 600,
        charges: 1,
        mlUse: 0,
        imgSrc: "/assets/imgs/runes/antidote.gif"
    },
    {
        name: "berserk",
        invocation: "adana pox",
        vocations: [1, 2],
        group: 2,
        isRune: false,
        isPremium: true,
        mlCast: 5,
        mana: "lvl * 4",
        price: 2500
    },
    {
        name: "cancel invisibility",
        invocation: "exana ina",
        vocations: [5, 6],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 12,
        mana: 250,
        price: 1600
    },
    {
        name: "challenge",
        invocation: "exeta res",
        vocations: [1, 2],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 4,
        mana: 90,
        price: 200
    },
    {
        name: "chameleon rune",
        invocation: "exeta res",
        vocations: [5, 6],
        group: 0,
        isRune: true,
        isPremium: false,
        mlCast: 11,
        mana: 150,
        price: 1300,
        charges: 1,
        mlUse: 4,
        imgSrc: "/assets/imgs/runes/chameleon.gif"
    },
    {
        name: "conjure arrow",
        invocation: "exevo con",
        vocations: [7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 2,
        mana: 40,
        price: 450
    },
    {
        name: "conjure bolt",
        invocation: "exevo con mort",
        vocations: [7, 8],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 6,
        mana: 70,
        price: 750
    },
    {
        name: "convince creature rune",
        invocation: "adeta sio",
        vocations: [5, 6],
        group: 0,
        isRune: true,
        isPremium: false,
        mlCast: 10,
        mana: 100,
        price: 1300,
        charges: 1,
        mlUse: 5,
        imgSrc: "/assets/imgs/runes/convince_creature.gif"
    },
    {
        name: "creature illusion",
        invocation: 'utevo res ina "creature"',
        vocations: [3, 4, 5, 6],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 10,
        mana: 100,
        price: 1000,
    },
    {
        name: "desintegrate rune",
        invocation: "adito tera",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: true,
        isPremium: true,
        mlCast: 8,
        mana: 100,
        price: 900,
        charges: 3,
        mlUse: 4,
        imgSrc: "/assets/imgs/runes/desintegrate.gif"
    },
    {
        name: "desintegrate",
        invocation: "exito tera",
        vocations: [5, 6],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 7,
        mana: 60,
        price: 500
    },
    {
        name: "destroy field rune",
        invocation: "adito grav",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: true,
        isPremium: false,
        mlCast: 6,
        mana: 60,
        price: 350,
        charges: 3,
        mlUse: 3,
        imgSrc: "/assets/imgs/runes/destroy_field.gif"
    },
    {
        name: "discharge",
        invocation: "exana vis",
        vocations: [5, 6],
        group: 1,
        isRune: false,
        isPremium: true,
        mlCast: 3,
        mana: 30,
        price: 300
    },
    {
        name: "enchant staff",
        invocation: "exeta vis",
        vocations: [3, 4],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 22,
        mana: 80,
        price: 2000
    },
    {
        name: "energy beam",
        invocation: "exevo vis lux",
        vocations: [3, 4],
        group: 2,
        isRune: false,
        isPremium: false,
        mlCast: 10,
        mana: 100,
        price: 1000
    },
    {
        name: "energy bomb rune",
        invocation: "adevo mas vis",
        vocations: [3, 4],
        group: 2,
        isRune: true,
        isPremium: true,
        mlCast: 18,
        mana: 220,
        price: 2300,
        charges: 2,
        mlUse: 10,
        imgSrc: "/assets/imgs/runes/energy_bomb.gif"
    },
    {
        name: "energy field rune",
        invocation: "adevo grav vis",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 5,
        mana: 80,
        price: 700,
        charges: 3,
        mlUse: 3,
        imgSrc: "/assets/imgs/runes/energy_field.gif"
    },
    {
        name: "energy strike",
        invocation: "exori vis",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: false,
        isPremium: true,
        mlCast: 3,
        mana: 20,
        price: 800
    },
    {
        name: "energy wall rune",
        invocation: "adevo mas grav vis",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 18,
        mana: 250,
        price: 2500,
        charges: 4,
        mlUse: 9,
        imgSrc: "/assets/imgs/runes/energy_wall.gif"
    },
    {
        name: "energy wave",
        invocation: "exevo mort hur",
        vocations: [3, 4],
        group: 2,
        isRune: false,
        isPremium: false,
        mlCast: 20,
        mana: 250,
        price: 2500
    },
    {
        name: "evenom rune",
        invocation: "adevo res pox",
        vocations: [5, 6],
        group: 2,
        isRune: true,
        isPremium: true,
        mlCast: 7,
        mana: 100,
        price: 1000,
        charges: 3,
        mlUse: 4,
        imgSrc: "/assets/imgs/runes/evenom.gif"
    },
    {
        name: "explosion rune",
        invocation: "adevo mas hur",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 12,
        mana: 180,
        price: 1800,
        charges: 3,
        mlUse: 6,
        imgSrc: "/assets/imgs/runes/explosion.gif"
    },
    {
        name: "explosive arrow",
        invocation: "exevo con flam",
        vocations: [7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 10,
        mana: 120,
        price: 1000
    },
    {
        name: "extinguish",
        invocation: "exana flam",
        vocations: [5, 6],
        group: 1,
        isRune: false,
        isPremium: true,
        mlCast: 3,
        mana: 30,
        price: 400
    },
    {
        name: "find person",
        invocation: 'exiva "name"',
        vocations: [1, 2, 3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 0,
        mana: 20,
        price: 80
    },
    {
        name: "fire field rune",
        invocation: "adevo grav flam",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 3,
        mana: 60,
        price: 500,
        charges: 3,
        mlUse: 1,
        imgSrc: "/assets/imgs/runes/fire_field.gif"
    },
    {
        name: "fire wall rune",
        invocation: "adevo mas grav flam",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 13,
        mana: 200,
        price: 200,
        charges: 4,
        mlUse: 6,
        imgSrc: "/assets/imgs/runes/fire_wall.gif"
    },
    {
        name: "fire wave",
        invocation: "exevo flam hur",
        vocations: [3, 4],
        group: 2,
        isRune: false,
        isPremium: false,
        mlCast: 7,
        mana: 80,
        price: 850
    },
    {
        name: "fireball rune",
        invocation: "adori flam",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 5,
        mana: 60,
        price: 800,
        charges: 3,
        mlUse: 2,
        imgSrc: "/assets/imgs/runes/fireball.gif"
    },
    {
        name: "fire bomb rune",
        invocation: "adevo mas flam",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 9,
        mana: 150,
        price: 1500,
        charges: 2,
        mlUse: 5,
        imgSrc: "/assets/imgs/runes/fire_bomb.gif"
    },
    {
        name: "flame strike",
        invocation: "exori flam",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: false,
        isPremium: true,
        mlCast: 3,
        mana: 20,
        price: 800
    },
    {
        name: "food",
        invocation: "exevo pan",
        vocations: [5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 0,
        mana: 30,
        price: 150
    },
    {
        name: "force strike",
        invocation: "exori mort",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: false,
        isPremium: true,
        mlCast: 2,
        mana: 20,
        price: 600
    },
    {
        name: "great energy beam",
        invocation: "exevo gran vis lux",
        vocations: [3, 4],
        group: 2,
        isRune: false,
        isPremium: false,
        mlCast: 14,
        mana: 200,
        price: 1800
    },
    {
        name: "great fireball rune",
        invocation: "adori gran flam",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 9,
        mana: 120,
        price: 1200,
        charges: 2,
        mlUse: 4,
        imgSrc: "/assets/imgs/runes/great_fireball.gif"
    },
    {
        name: "great light",
        invocation: "utevo gran lux",
        vocations: [1, 2, 3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 3,
        mana: 60,
        price: 500
    },
    {
        name: "haste",
        invocation: "utani hur",
        vocations: [1, 2, 3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 4,
        mana: 60,
        price: 600
    },
    {
        name: "heal friend",
        invocation: 'exura sio "name"',
        vocations: [5, 6],
        group: 1,
        isRune: false,
        isPremium: true,
        mlCast: 7,
        mana: 70,
        price: 800
    },
    {
        name: "heavy magic missile rune",
        invocation: "adori gran",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 3,
        mana: 70,
        price: 600,
        charges: 5,
        mlUse: 1,
        imgSrc: "/assets/imgs/runes/heavy_magic_missile.gif"
    },
    {
        name: "intense healing",
        invocation: "exura gran",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 1,
        isRune: false,
        isPremium: false,
        mlCast: 2,
        mana: 40,
        price: 350
    },
    {
        name: "intense healing rune",
        invocation: "adura gran",
        vocations: [5, 6],
        group: 1,
        isRune: true,
        isPremium: false,
        mlCast: 4,
        mana: 60,
        price: 600,
        charges: 1,
        mlUse: 1,
        imgSrc: "/assets/imgs/runes/intense_healing.gif"
    },
    {
        name: "invisible",
        invocation: "utana vid",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 15,
        mana: 210,
        price: 1000
    },
    {
        name: "levitate",
        invocation: 'exani hur "up|down"',
        vocations: [1, 2, 3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 3,
        mana: 50,
        price: 500
    },
    {
        name: "light",
        invocation: "utevo lux",
        vocations: [1, 2, 3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 0,
        mana: 20,
        price: 100
    },
    {
        name: "light healing",
        invocation: "exura",
        vocations: [1, 2, 3, 4, 5, 6, 7, 8],
        group: 1,
        isRune: false,
        isPremium: false,
        mlCast: 1,
        mana: 25,
        price: 170
    },
    {
        name: "light magic missile rune",
        invocation: "adori",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 1,
        mana: 40,
        price: 200,
        charges: 5,
        mlUse: 0,
        imgSrc: "/assets/imgs/runes/light_magic_missile.gif"
    },
    {
        name: "magic rope",
        invocation: "exani tera",
        vocations: [1, 2, 3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 1,
        mana: 20,
        price: 200
    },
    {
        name: "magic shield",
        invocation: "utamo vita",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 4,
        mana: 50,
        price: 450
    },
    {
        name: "magic wall rune",
        invocation: "utamo vita",
        vocations: [3, 4],
        group: 0,
        isRune: true,
        isPremium: true,
        mlCast: 14,
        mana: 250,
        price: 2100,
        charges: 4,
        mlUse: 9,
        imgSrc: "/assets/imgs/runes/magic_wall.gif"
    },
    {
        name: "mass healing",
        invocation: "exura gran mas res",
        vocations: [5, 6],
        group: 1,
        isRune: false,
        isPremium: true,
        mlCast: 19,
        mana: 120,
        price: 2200
    },
    {
        name: "paralyze rune",
        invocation: "adana ani",
        vocations: [5, 6],
        group: 0,
        isRune: true,
        isPremium: true,
        mlCast: 35,
        mana: 600,
        price: 1900,
        charges: 1,
        mlUse: 18,
        imgSrc: "/assets/imgs/runes/paralyze.gif"
    },
    {
        name: "poison field rune",
        invocation: "adevo grav pox",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 2,
        mana: 50,
        price: 300,
        charges: 3,
        mlUse: 0,
        imgSrc: "/assets/imgs/runes/poison_field.gif"
    },
    {
        name: "poison storm",
        invocation: "exevo gran mas pox",
        vocations: [5, 6],
        group: 2,
        isRune: false,
        isPremium: true,
        mlCast: 28,
        mana: 400,
        price: 3400
    },
    {
        name: "poison wall rune",
        invocation: "adevo mas grav pox",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 11,
        mana: 160,
        price: 1600,
        charges: 4,
        mlUse: 5,
        imgSrc: "/assets/imgs/runes/poison_wall.gif"
    },
    {
        name: "poison bomb rune",
        invocation: "adevo mas pox",
        vocations: [5, 6],
        group: 2,
        isRune: true,
        isPremium: true,
        mlCast: 8,
        mana: 130,
        price: 1000,
        charges: 2,
        mlUse: 4,
        imgSrc: "/assets/imgs/runes/poison_bomb.gif"
    },
    {
        name: "poisoned arrow",
        invocation: "exevo con pox",
        vocations: [7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 5,
        mana: 70,
        price: 700
    },
    {
        name: "power bolt",
        invocation: "exevo con vis",
        vocations: [7, 8],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 14,
        mana: 200,
        price: 2000
    },
    {
        name: "soulfire rune",
        invocation: "adevo res flam",
        vocations: [3, 4, 5, 6],
        group: 2,
        isRune: true,
        isPremium: true,
        mlCast: 13,
        mana: 150,
        price: 1800,
        charges: 2,
        mlUse: 7,
        imgSrc: "/assets/imgs/runes/soulfire.gif"
    },
    {
        name: "strong haste",
        invocation: "utani gran hur",
        vocations: [3, 4, 5, 6],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 8,
        mana: 100,
        price: 1300
    },
    {
        name: "sudden death rune",
        invocation: "adori vita vis",
        vocations: [3, 4],
        group: 2,
        isRune: true,
        isPremium: false,
        mlCast: 25,
        mana: 220,
        price: 3000,
        charges: 1,
        mlUse: 15,
        imgSrc: "/assets/imgs/runes/sudden_death.gif"
    },
    {
        name: "summon creature",
        invocation: 'utevo res "creature"',
        vocations: [3, 4, 5, 6],
        group: 0,
        isRune: false,
        isPremium: false,
        mlCast: 16,
        price: 2000
    },
    {
        name: "ultimate explosion",
        invocation: "exevo gran mas vis",
        vocations: [3, 4],
        group: 2,
        isRune: false,
        isPremium: true,
        mlCast: 40,
        mana: 800,
        price: 8000
    },
    {
        name: "ultimate healing",
        invocation: "exura vita",
        vocations: [3, 4, 5, 6, 7, 8],
        group: 1,
        isRune: false,
        isPremium: false,
        mlCast: 8,
        mana: 80,
        price: 1000
    },
    {
        name: "ultimate healing rune",
        invocation: "adura vita",
        vocations: [5, 6],
        group: 1,
        isRune: true,
        isPremium: false,
        mlCast: 11,
        mana: 100,
        price: 1500,
        charges: 1,
        mlUse: 4,
        imgSrc: "/assets/imgs/runes/ultimate_healing.gif"
    },
    {
        name: "ultimate light",
        invocation: "utevo vis lux",
        vocations: [3, 4, 5, 6],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 12,
        mana: 140,
        price: 1600
    },
    {
        name: "undead legion",
        invocation: "exana mas mort",
        vocations: [5, 6],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 15,
        mana: 400,
        price: 2000
    },
    {
        name: "wild growth",
        invocation: "exevo grav vita",
        vocations: [5, 6],
        group: 0,
        isRune: false,
        isPremium: true,
        mlCast: 13,
        mana: 150,
        price: 2000
    }
]

module.exports = spells