const swords = [
    {
        name: "bone sword",
        atk: 14,
        def: 10,
        weight: 19.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/bone_sword.gif',
    },
    {
        name: "bright sword",
        atk: 36,
        def: 30,
        weight: 29.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/bright_sword.gif',
    },
    {
        name: "broadsword",
        atk: 26,
        def: 23,
        weight: 29.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/swords/broadsword.gif',
    },
    {
        name: "carlin sword",
        atk: 15,
        def: 13,
        weight: 40.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/carlin_sword.gif',
    },
    {
        name: "combat knife",
        atk: 8,
        def: 6,
        weight: 8.7,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/combat_knife.gif',
    },
    {
        name: "dagger",
        atk: 8,
        def: 6,
        weight: 9.5,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/dagger.gif',
    },
    {
        name: "djinn blade",
        atk: 38,
        def: 22,
        weight: 24.5,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/djinn_blade.gif',
    },
    {
        name: "fire sword",
        atk: 35,
        def: 20,
        weight: 23.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/fire_sword.gif',
    },
    {
        name: "foil",
        atk: 9,
        def: 11,
        weight: 14.5,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/foil.gif',
    },
    {
        name: "giant sword",
        atk: 46,
        def: 22,
        weight: 180,
        twoHanded: true,
        imageSrc: '/assets/imgs/swords/giant_sword.gif',
    },
    {
        name: "heavy machete",
        atk: 16,
        def: 10,
        weight: 18.4,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/heavy_machete.gif',
    },
    {
        name: "ice rapier",
        atk: 100,
        def: 1,
        weight: 15.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/ice_rapier.gif',
    },
    {
        name: "katana",
        atk: 16,
        def: 12,
        weight: 31.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/katana.gif',
    },
    {
        name: "knife",
        atk: 7,
        def: 5,
        weight: 4.2,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/katana.gif',
    },
    {
        name: "longsword",
        atk: 17,
        def: 14,
        weight: 42.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/longsword.gif',
    },
    {
        name: "machete",
        atk: 12,
        def: 9,
        weight: 16.5,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/machete.gif',
    },
    {
        name: "magic longsword",
        atk: 55,
        def: 40,
        weight: 43.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/swords/magic_longsword.gif',
    },
    {
        name: "pharaoh sword",
        atk: 41,
        def: 23,
        weight: 52.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/pharaoh_sword.gif',
    },
    {
        name: "poison dagger",
        atk: 18,
        def: 8,
        weight: 8.8,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/poison_dagger.gif',
    },
    {
        name: "rapier",
        atk: 10,
        def: 8,
        weight: 15.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/rapier.gif',
    },
    {
        name: "sabre",
        atk: 12,
        def: 10,
        weight: 25.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/sabre.gif',
    },
    {
        name: "scimitar",
        atk: 19,
        def: 13,
        weight: 29.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/scimitar.gif',
    },
    {
        name: "serpent sword",
        atk: 26,
        def: 15,
        weight: 41.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/serpent_sword.gif',
    },
    {
        name: "short sword",
        atk: 11,
        def: 11,
        weight: 35.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/short_sword.gif',
    },
    {
        name: "silver dagger",
        atk: 8,
        def: 7,
        weight: 10.2,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/silver_dagger.gif',
    },
    {
        name: "spike sword",
        atk: 24,
        def: 21,
        weight: 50.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/spike_sword.gif',
    },
    {
        name: "sword",
        atk: 14,
        def: 12,
        weight: 35.0,
        twoHanded: false,
        imageSrc: '/assets/imgs/swords/sword.gif',
    },
    {
        name: "two handed sword",
        atk: 30,
        def: 25,
        weight: 70.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/swords/two_handed_sword.gif',
    },
    {
        name: "warlord sword",
        atk: 53,
        def: 38,
        weight: 64.0,
        twoHanded: true,
        imageSrc: '/assets/imgs/swords/warlord_sword.gif',
    }
]

module.exports = swords